# Generated by Django 5.0 on 2024-12-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appraisal',
            options={'verbose_name': 'nyrhnama', 'verbose_name_plural': 'nyrhnamalar'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'abonent', 'verbose_name_plural': 'abonentler'},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'verbose_name': 'bukja', 'verbose_name_plural': 'bukjalar'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'hyzmat', 'verbose_name_plural': 'hyzmatlar'},
        ),
        migrations.AlterField(
            model_name='client',
            name='packages',
            field=models.ManyToManyField(blank=True, to='main.package'),
        ),
        migrations.AlterField(
            model_name='client',
            name='services',
            field=models.ManyToManyField(blank=True, to='main.service'),
        ),
    ]
