# Generated by Django 5.0 on 2024-12-10 11:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_client_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ends_at', models.DateTimeField(default=datetime.datetime(2025, 1, 9, 11, 32, 51, 897691, tzinfo=datetime.timezone.utc))),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.client')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.package')),
            ],
        ),
    ]
