# Generated by Django 5.0 on 2024-12-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_clientpackage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientpackage',
            options={'verbose_name': 'ulanyjy bukjasy', 'verbose_name_plural': 'ulanyjy bukjalary'},
        ),
        migrations.AlterField(
            model_name='clientpackage',
            name='ends_at',
            field=models.DateTimeField(),
        ),
    ]
