# Generated by Django 5.0 on 2024-12-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_clientpackage_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='packages',
        ),
    ]
