# Generated by Django 5.0 on 2024-12-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_client_packages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='package',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
    ]
